const jobs = [
  {
    id: 1,
    slug: "senior-program-manager",
    title: "Senior Program Manager",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at velit euismod, porta sem et, molestie felis...",
    category: "Technology Engineering",
    status: "Full Time",
    primarySkills: ["Qliksense BI Automation Testing"],
    mustHaveSkills: ["Qliksense BI Tool -Automation", "Core Java"],
    experience: "3+ Years",
    location: "Pan India",
    responsibility: "The associate has basic awareness and comprehension...",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-05",
  },
  {
    id: 2,
    slug: "cloud-engineer",
    title: "Cloud Engineer",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at velit euismod...",
    category: "Cloud",
    status: "Full Time",
    primarySkills: ["AWS", "Azure"],
    mustHaveSkills: ["Docker", "Kubernetes"],
    experience: "2+ Years",
    location: "Bangalore",
    responsibility: "Cloud architecture support...",
    shift: "Night Shift",
    travel: "No",
    postingDate: "2024-01-06",
  },
  {
    id: 3,
    slug: "ai-analyst",
    title: "AI Analyst",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "AI & Data Science",
    status: "Full Time",
    primarySkills: ["Python", "ML"],
    mustHaveSkills: ["NLP", "TensorFlow"],
    experience: "4+ Years",
    location: "Delhi",
    responsibility: "Data analysis and model creation",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-08",
  },
  {
    id: 4,
    slug: "frontend-developer",
    title: "Frontend Developer",
    description: "React-based UI development, performance optimization...",
    category: "Software Development",
    status: "Full Time",
    primarySkills: ["React", "TypeScript"],
    mustHaveSkills: ["Redux", "REST APIs"],
    experience: "2+ Years",
    location: "Mumbai",
    responsibility: "Build scalable UI components",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-10",
  },
  {
    id: 5,
    slug: "backend-node-js-developer",
    title: "Backend Node.js Developer",
    description: "Node.js API development with high performance...",
    category: "Software Development",
    status: "Full Time",
    primarySkills: ["Node.js", "MongoDB"],
    mustHaveSkills: ["Express.js", "Redis"],
    experience: "3+ Years",
    location: "Hyderabad",
    responsibility: "Develop server applications & API integrations",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-12",
  },
  {
    id: 6,
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    description: "Design web and mobile UI screens...",
    category: "Creative & Design",
    status: "Full Time",
    primarySkills: ["Figma", "Adobe XD"],
    mustHaveSkills: ["User Research", "Wireframing"],
    experience: "1+ Years",
    location: "Pune",
    responsibility: "Collaborate with development teams",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-14",
  },
  {
    id: 7,
    slug: "digital-marketing-specialist",
    title: "Digital Marketing Specialist",
    description: "SEO & campaign management responsibilities...",
    category: "Marketing",
    status: "Full Time",
    primarySkills: ["SEO", "Google Ads"],
    mustHaveSkills: ["Analytics", "Content Strategy"],
    experience: "2+ Years",
    location: "Remote",
    responsibility: "Lead digital campaign execution",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-18",
  },
  {
    id: 8,
    slug: "hr-recruiter",
    title: "HR Recruiter",
    description: "Hiring and onboarding responsibilities...",
    category: "Human Resources",
    status: "Full Time",
    primarySkills: ["Talent Acquisition"],
    mustHaveSkills: ["Communication Skills", "LinkedIn Hiring"],
    experience: "1+ Years",
    location: "Chennai",
    responsibility: "Manage end-to-end recruitment",
    shift: "Day Job",
    travel: "Yes",
    postingDate: "2024-01-20",
  },
  {
    id: 9,
    slug: "flutter-mobile-developer",
    title: "Flutter Mobile Developer",
    description: "Build cross-platform mobile apps...",
    category: "Mobile Development",
    status: "Full Time",
    primarySkills: ["Flutter", "Dart"],
    mustHaveSkills: ["REST APIs", "Firebase"],
    experience: "2+ Years",
    location: "Kolkata",
    responsibility: "App development and maintenance",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-21",
  },
  {
    id: 10,
    slug: "cyber-security-analyst",
    title: "Cyber Security Analyst",
    description: "Security audits & monitoring...",
    category: "Security",
    status: "Full Time",
    primarySkills: ["SIEM", "Firewalls"],
    mustHaveSkills: ["Risk Analysis", "Incident Response"],
    experience: "3+ Years",
    location: "Mumbai",
    responsibility: "Protect systems from threats",
    shift: "Night Shift",
    travel: "No",
    postingDate: "2024-01-22",
  },
  {
    id: 11,
    slug: "devops-engineer",
    title: "DevOps Engineer",
    description: "CI/CD automation for deployments...",
    category: "DevOps",
    status: "Full Time",
    primarySkills: ["AWS", "Jenkins"],
    mustHaveSkills: ["Terraform", "Docker"],
    experience: "4+ Years",
    location: "Remote",
    responsibility: "Automate pipelines & environments",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-24",
  },
  {
    id: 12,
    slug: "business-analyst",
    title: "Business Analyst",
    description: "Requirement gathering & client presentation...",
    category: "Business Operations",
    status: "Full Time",
    primarySkills: ["Documentation", "BPMN"],
    mustHaveSkills: ["Agile", "SCRUM"],
    experience: "2+ Years",
    location: "Delhi",
    responsibility: "Bridge between clients and developers",
    shift: "Day Job",
    travel: "Yes",
    postingDate: "2024-01-25",
  },
  {
    id: 13,
    slug: "sales-executive",
    title: "Sales Executive",
    description: "Lead generation and client meetings...",
    category: "Sales",
    status: "Full Time",
    primarySkills: ["CRM", "Cold Calling"],
    mustHaveSkills: ["Negotiation", "Presentation"],
    experience: "1+ Years",
    location: "Surat",
    responsibility: "Generate and convert leads",
    shift: "Day Job",
    travel: "Yes",
    postingDate: "2024-01-26",
  },
  {
    id: 14,
    slug: "product-manager",
    title: "Product Manager",
    description: "Define roadmap & lead execution...",
    category: "Management",
    status: "Full Time",
    primarySkills: ["Roadmap Planning"],
    mustHaveSkills: ["Agile", "Market Research"],
    experience: "5+ Years",
    location: "Bangalore",
    responsibility: "Product lifecycle management",
    shift: "Day Job",
    travel: "Yes",
    postingDate: "2024-01-28",
  },
  {
    id: 15,
    slug: "intern-software-engineer",
    title: "Intern Software Engineer",
    description: "Assist development team",
    category: "Internship",
    status: "Internship",
    primarySkills: ["JavaScript"],
    mustHaveSkills: ["Basic Algorithms"],
    experience: "0-1 Years",
    location: "Noida",
    responsibility: "Support team in coding",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-01-30",
  },
  {
    id: 16,
    slug: "java-full-stack-developer",
    title: "Java Full-Stack Developer",
    description: "Spring Boot + Angular full-stack role",
    category: "Software Development",
    status: "Full Time",
    primarySkills: ["Java", "Spring Boot"],
    mustHaveSkills: ["Angular", "MySQL"],
    experience: "3+ Years",
    location: "Hyderabad",
    responsibility: "Develop & integrate systems",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-01",
  },
  {
    id: 17,
    slug: "etl-developer",
    title: "ETL Developer",
    description: "Data pipeline development & management",
    category: "Data Engineering",
    status: "Full Time",
    primarySkills: ["Informatica", "ETL Tools"],
    mustHaveSkills: ["SQL Server", "SSIS"],
    experience: "4+ Years",
    location: "Chandigarh",
    responsibility: "Develop ETL workflows",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-03",
  },
  {
    id: 18,
    slug: "network-engineer",
    title: "Network Engineer",
    description: "Network infrastructure monitoring",
    category: "Networking",
    status: "Full Time",
    primarySkills: ["LAN/WAN", "CISCO Routing"],
    mustHaveSkills: ["Troubleshooting"],
    experience: "2+ Years",
    location: "Ahmedabad",
    responsibility: "Maintain networking environment",
    shift: "Night Shift",
    travel: "Yes",
    postingDate: "2024-02-04",
  },
  {
    id: 19,
    slug: "machine-learning-engineer",
    title: "Machine Learning Engineer",
    description: "ML model development & evaluation",
    category: "AI & Data Science",
    status: "Full Time",
    primarySkills: ["Python", "PyTorch"],
    mustHaveSkills: ["Model Deployment", "ML Ops"],
    experience: "3+ Years",
    location: "Gurgaon",
    responsibility: "Train and deploy ML models",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-06",
  },
  {
    id: 20,
    slug: "content-writer",
    title: "Content Writer",
    description: "Write blogs, articles, and website content",
    category: "Content & Writing",
    status: "Part Time",
    primarySkills: ["Copywriting"],
    mustHaveSkills: ["SEO Writing"],
    experience: "1+ Years",
    location: "Remote",
    responsibility: "Create optimized content",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-08",
  },
  {
    id: 21,
    slug: "finance-manager",
    title: "Finance Manager",
    description: "Financial compliance & reporting",
    category: "Finance",
    status: "Full Time",
    primarySkills: ["Budgeting", "Tax"],
    mustHaveSkills: ["Accounting", "Tally"],
    experience: "5+ Years",
    location: "Mumbai",
    responsibility: "Manage financial planning",
    shift: "Day Job",
    travel: "Yes",
    postingDate: "2024-02-10",
  },
  {
    id: 22,
    slug: "sap-consultant",
    title: "SAP Consultant",
    description: "SAP ERP support & customization",
    category: "ERP Consulting",
    status: "Full Time",
    primarySkills: ["SAP FICO", "SAP ABAP"],
    mustHaveSkills: ["Implementation", "Support"],
    experience: "3+ Years",
    location: "Pune",
    responsibility: "Manage ERP systems",
    shift: "Day Job",
    travel: "Yes",
    postingDate: "2024-02-12",
  },
  {
    id: 23,
    slug: "customer-support-executive",
    title: "Customer Support Executive",
    description: "Handle support requests",
    category: "Support",
    status: "Full Time",
    primarySkills: ["Communication", "Ticketing Systems"],
    mustHaveSkills: ["Email Support"],
    experience: "1+ Years",
    location: "Jaipur",
    responsibility: "Resolve support queries",
    shift: "Night Shift",
    travel: "No",
    postingDate: "2024-02-14",
  },
  {
    id: 24,
    slug: "graphic-designer",
    title: "Graphic Designer",
    description: "Branding & graphics creation",
    category: "Creative & Design",
    status: "Part Time",
    primarySkills: ["Photoshop", "Illustrator"],
    mustHaveSkills: ["Branding", "Creativity"],
    experience: "1.5+ Years",
    location: "Remote",
    responsibility: "Create design assets",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-15",
  },
  {
    id: 25,
    slug: "power-bi-developer",
    title: "Power BI Developer",
    description: "Dashboards and analytics",
    category: "Business Intelligence",
    status: "Full Time",
    primarySkills: ["Power BI", "DAX"],
    mustHaveSkills: ["SQL", "ETL"],
    experience: "2+ Years",
    location: "Noida",
    responsibility: "Build BI dashboards",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-17",
  },
  {
    id: 26,
    slug: "database-administrator",
    title: "Database Administrator",
    description: "Database performance management",
    category: "Database",
    status: "Full Time",
    primarySkills: ["MySQL", "PostgreSQL"],
    mustHaveSkills: ["Backup & Restore", "Monitoring"],
    experience: "4+ Years",
    location: "Kochi",
    responsibility: "Manage DB clusters",
    shift: "Night Shift",
    travel: "No",
    postingDate: "2024-02-18",
  },
  {
    id: 27,
    slug: "data-entry-operator",
    title: "Data Entry Operator",
    description: "Maintaining data records",
    category: "Operations",
    status: "Contract",
    primarySkills: ["MS Excel"],
    mustHaveSkills: ["Typing", "Accuracy"],
    experience: "0-1 Years",
    location: "Indore",
    responsibility: "Handle data entry",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-19",
  },
  {
    id: 28,
    slug: "php-developer",
    title: "PHP Developer",
    description: "Backend development & CMS customization",
    category: "Software Development",
    status: "Full Time",
    primarySkills: ["PHP", "Laravel"],
    mustHaveSkills: ["MySQL", "API Development"],
    experience: "3+ Years",
    location: "Nagpur",
    responsibility: "Build scalable backend apps",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-20",
  },
  {
    id: 29,
    slug: "video-editor",
    title: "Video Editor",
    description: "Video editing for branding and marketing",
    category: "Media & Video Editing",
    status: "Part Time",
    primarySkills: ["Premiere Pro", "After Effects"],
    mustHaveSkills: ["Motion Graphics"],
    experience: "1+ Years",
    location: "Remote",
    responsibility: "Edit promotional videos",
    shift: "Day Job",
    travel: "No",
    postingDate: "2024-02-21",
  },
  {
    id: 30,
    slug: "project-coordinator",
    title: "Project Coordinator",
    description: "Supporting project execution and communication",
    category: "Project Management",
    status: "Full Time",
    primarySkills: ["Documentation"],
    mustHaveSkills: ["Team Coordination", "Scheduling"],
    experience: "2+ Years",
    location: "Lucknow",
    responsibility: "Assist project teams",
    shift: "Day Job",
    travel: "Yes",
    postingDate: "2024-02-22",
  },
];

export default jobs;
